### ISSUE TITLE
This new rule means that the mobile version does not display correctly.

### ISSUE THREAD

**Issue by frodrisan** [20H-Talent/ikigai-project-2-project2-marolyn-fabian#5]
https://github.com/20H-Talent/ikigai-project-2-project2-marolyn-fabian/blob/008735bc944a5af4754c568a0746a1d6285336e6/css/styles.css#L112

**Comment by MarolynDayan** [comment]
this rule make the footer p (now the footer ul) works like the p bottom footer rigth
