### ISSUE TITLE
Missing spacing 

### ISSUE THREAD

**Issue by manuhdez** [20H-Talent/ikigai-project-2-project2-marolyn-fabian#9]
@MarolynDayan 
https://github.com/20H-Talent/ikigai-project-2-project2-marolyn-fabian/blob/6dce62b2ff1356310149cd239f811c169ebe0f24/index.html#L33

**Comment by frodrisan** [comment]
Padding/margin doesn't look as it does in the project's mockups.
The navigation bar in the top is upside down.
